services:
  db:
    container_name: the_db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"

  app:
    #pull'er fra mit ghcr image
    image: ghcr.io/sumayaiaden1/tekdemo2
    restart: unless-stopped
    ports:
      - "127.0.0.1:8081:8080"