name: Java CI

#Triggers
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch: # manual trigger

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0, 2025-08-11

      - name: Set JDK
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0, 2025-08-21
        with:
          java-version: "21"
          distribution: "temurin"

      # Cache 3rd-party Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      # Cache .class files (build output)
      - name: Cache compiled classes
        uses: actions/cache@v4
        with:
          path: target
          key: classes-${{ runner.os }}-${{ github.sha }}


      - name: Run tests
        run: mvn -B test # -B for batch mode, ingen bruger input